apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
#daqui pra cima é um ReplicaSet
#daqui pra baixo é passado um pod.
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name:  nginx
        image: nginx
        ports:
          - containerPort: 80
